
springdoc:
    packagesToScan: com.brqtest

spring:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test2
    username: sa
    password:
    driverClassName: org.h2.Driver